# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/forks/Retro68

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/forks/Retro68-build/build-target

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/forks/Retro68-build/build-target/CMakeFiles /root/forks/Retro68-build/build-target/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/forks/Retro68-build/build-target/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named retrocrt

# Build rule for target.
retrocrt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 retrocrt
.PHONY : retrocrt

# fast build rule for target.
retrocrt/fast:
	$(MAKE) -f libretro/CMakeFiles/retrocrt.dir/build.make libretro/CMakeFiles/retrocrt.dir/build
.PHONY : retrocrt/fast

#=============================================================================
# Target rules for targets named ConsoleTest

# Build rule for target.
ConsoleTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ConsoleTest
.PHONY : ConsoleTest

# fast build rule for target.
ConsoleTest/fast:
	$(MAKE) -f Console/CMakeFiles/ConsoleTest.dir/build.make Console/CMakeFiles/ConsoleTest.dir/build
.PHONY : ConsoleTest/fast

#=============================================================================
# Target rules for targets named RetroConsole

# Build rule for target.
RetroConsole: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RetroConsole
.PHONY : RetroConsole

# fast build rule for target.
RetroConsole/fast:
	$(MAKE) -f Console/CMakeFiles/RetroConsole.dir/build.make Console/CMakeFiles/RetroConsole.dir/build
.PHONY : RetroConsole/fast

#=============================================================================
# Target rules for targets named ConsoleTest_APPL

# Build rule for target.
ConsoleTest_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ConsoleTest_APPL
.PHONY : ConsoleTest_APPL

# fast build rule for target.
ConsoleTest_APPL/fast:
	$(MAKE) -f Console/CMakeFiles/ConsoleTest_APPL.dir/build.make Console/CMakeFiles/ConsoleTest_APPL.dir/build
.PHONY : ConsoleTest_APPL/fast

#=============================================================================
# Target rules for targets named HelloWorld

# Build rule for target.
HelloWorld: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HelloWorld
.PHONY : HelloWorld

# fast build rule for target.
HelloWorld/fast:
	$(MAKE) -f Samples/HelloWorld/CMakeFiles/HelloWorld.dir/build.make Samples/HelloWorld/CMakeFiles/HelloWorld.dir/build
.PHONY : HelloWorld/fast

#=============================================================================
# Target rules for targets named HelloWorld_APPL

# Build rule for target.
HelloWorld_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HelloWorld_APPL
.PHONY : HelloWorld_APPL

# fast build rule for target.
HelloWorld_APPL/fast:
	$(MAKE) -f Samples/HelloWorld/CMakeFiles/HelloWorld_APPL.dir/build.make Samples/HelloWorld/CMakeFiles/HelloWorld_APPL.dir/build
.PHONY : HelloWorld_APPL/fast

#=============================================================================
# Target rules for targets named AsmTest_APPL

# Build rule for target.
AsmTest_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AsmTest_APPL
.PHONY : AsmTest_APPL

# fast build rule for target.
AsmTest_APPL/fast:
	$(MAKE) -f TestApps/CMakeFiles/AsmTest_APPL.dir/build.make TestApps/CMakeFiles/AsmTest_APPL.dir/build
.PHONY : AsmTest_APPL/fast

#=============================================================================
# Target rules for targets named EmptyTest_APPL

# Build rule for target.
EmptyTest_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EmptyTest_APPL
.PHONY : EmptyTest_APPL

# fast build rule for target.
EmptyTest_APPL/fast:
	$(MAKE) -f TestApps/CMakeFiles/EmptyTest_APPL.dir/build.make TestApps/CMakeFiles/EmptyTest_APPL.dir/build
.PHONY : EmptyTest_APPL/fast

#=============================================================================
# Target rules for targets named EmptyTest

# Build rule for target.
EmptyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EmptyTest
.PHONY : EmptyTest

# fast build rule for target.
EmptyTest/fast:
	$(MAKE) -f TestApps/CMakeFiles/EmptyTest.dir/build.make TestApps/CMakeFiles/EmptyTest.dir/build
.PHONY : EmptyTest/fast

#=============================================================================
# Target rules for targets named ExceptionTest

# Build rule for target.
ExceptionTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExceptionTest
.PHONY : ExceptionTest

# fast build rule for target.
ExceptionTest/fast:
	$(MAKE) -f TestApps/CMakeFiles/ExceptionTest.dir/build.make TestApps/CMakeFiles/ExceptionTest.dir/build
.PHONY : ExceptionTest/fast

#=============================================================================
# Target rules for targets named ExceptionTest_APPL

# Build rule for target.
ExceptionTest_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExceptionTest_APPL
.PHONY : ExceptionTest_APPL

# fast build rule for target.
ExceptionTest_APPL/fast:
	$(MAKE) -f TestApps/CMakeFiles/ExceptionTest_APPL.dir/build.make TestApps/CMakeFiles/ExceptionTest_APPL.dir/build
.PHONY : ExceptionTest_APPL/fast

#=============================================================================
# Target rules for targets named AsmTest

# Build rule for target.
AsmTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AsmTest
.PHONY : AsmTest

# fast build rule for target.
AsmTest/fast:
	$(MAKE) -f TestApps/CMakeFiles/AsmTest.dir/build.make TestApps/CMakeFiles/AsmTest.dir/build
.PHONY : AsmTest/fast

#=============================================================================
# Target rules for targets named InitTest

# Build rule for target.
InitTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 InitTest
.PHONY : InitTest

# fast build rule for target.
InitTest/fast:
	$(MAKE) -f TestApps/CMakeFiles/InitTest.dir/build.make TestApps/CMakeFiles/InitTest.dir/build
.PHONY : InitTest/fast

#=============================================================================
# Target rules for targets named InitTest_APPL

# Build rule for target.
InitTest_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 InitTest_APPL
.PHONY : InitTest_APPL

# fast build rule for target.
InitTest_APPL/fast:
	$(MAKE) -f TestApps/CMakeFiles/InitTest_APPL.dir/build.make TestApps/CMakeFiles/InitTest_APPL.dir/build
.PHONY : InitTest_APPL/fast

#=============================================================================
# Target rules for targets named Dialog

# Build rule for target.
Dialog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Dialog
.PHONY : Dialog

# fast build rule for target.
Dialog/fast:
	$(MAKE) -f Samples/Dialog/CMakeFiles/Dialog.dir/build.make Samples/Dialog/CMakeFiles/Dialog.dir/build
.PHONY : Dialog/fast

#=============================================================================
# Target rules for targets named Dialog_APPL

# Build rule for target.
Dialog_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Dialog_APPL
.PHONY : Dialog_APPL

# fast build rule for target.
Dialog_APPL/fast:
	$(MAKE) -f Samples/Dialog/CMakeFiles/Dialog_APPL.dir/build.make Samples/Dialog/CMakeFiles/Dialog_APPL.dir/build
.PHONY : Dialog_APPL/fast

#=============================================================================
# Target rules for targets named Raytracer_APPL

# Build rule for target.
Raytracer_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Raytracer_APPL
.PHONY : Raytracer_APPL

# fast build rule for target.
Raytracer_APPL/fast:
	$(MAKE) -f Samples/Raytracer/CMakeFiles/Raytracer_APPL.dir/build.make Samples/Raytracer/CMakeFiles/Raytracer_APPL.dir/build
.PHONY : Raytracer_APPL/fast

#=============================================================================
# Target rules for targets named Raytracer

# Build rule for target.
Raytracer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Raytracer
.PHONY : Raytracer

# fast build rule for target.
Raytracer/fast:
	$(MAKE) -f Samples/Raytracer/CMakeFiles/Raytracer.dir/build.make Samples/Raytracer/CMakeFiles/Raytracer.dir/build
.PHONY : Raytracer/fast

#=============================================================================
# Target rules for targets named Raytracer2

# Build rule for target.
Raytracer2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Raytracer2
.PHONY : Raytracer2

# fast build rule for target.
Raytracer2/fast:
	$(MAKE) -f Samples/Raytracer/CMakeFiles/Raytracer2.dir/build.make Samples/Raytracer/CMakeFiles/Raytracer2.dir/build
.PHONY : Raytracer2/fast

#=============================================================================
# Target rules for targets named FixedBenchmark

# Build rule for target.
FixedBenchmark: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FixedBenchmark
.PHONY : FixedBenchmark

# fast build rule for target.
FixedBenchmark/fast:
	$(MAKE) -f Samples/Raytracer/CMakeFiles/FixedBenchmark.dir/build.make Samples/Raytracer/CMakeFiles/FixedBenchmark.dir/build
.PHONY : FixedBenchmark/fast

#=============================================================================
# Target rules for targets named Raytracer2_APPL

# Build rule for target.
Raytracer2_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Raytracer2_APPL
.PHONY : Raytracer2_APPL

# fast build rule for target.
Raytracer2_APPL/fast:
	$(MAKE) -f Samples/Raytracer/CMakeFiles/Raytracer2_APPL.dir/build.make Samples/Raytracer/CMakeFiles/Raytracer2_APPL.dir/build
.PHONY : Raytracer2_APPL/fast

#=============================================================================
# Target rules for targets named FixedBenchmark_APPL

# Build rule for target.
FixedBenchmark_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FixedBenchmark_APPL
.PHONY : FixedBenchmark_APPL

# fast build rule for target.
FixedBenchmark_APPL/fast:
	$(MAKE) -f Samples/Raytracer/CMakeFiles/FixedBenchmark_APPL.dir/build.make Samples/Raytracer/CMakeFiles/FixedBenchmark_APPL.dir/build
.PHONY : FixedBenchmark_APPL/fast

#=============================================================================
# Target rules for targets named PicPuzzle

# Build rule for target.
PicPuzzle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PicPuzzle
.PHONY : PicPuzzle

# fast build rule for target.
PicPuzzle/fast:
	$(MAKE) -f Samples/Project3/CMakeFiles/PicPuzzle.dir/build.make Samples/Project3/CMakeFiles/PicPuzzle.dir/build
.PHONY : PicPuzzle/fast

#=============================================================================
# Target rules for targets named WDEF

# Build rule for target.
WDEF: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WDEF
.PHONY : WDEF

# fast build rule for target.
WDEF/fast:
	$(MAKE) -f Samples/Project3/CMakeFiles/WDEF.dir/build.make Samples/Project3/CMakeFiles/WDEF.dir/build
.PHONY : WDEF/fast

#=============================================================================
# Target rules for targets named PicPuzzle_APPL

# Build rule for target.
PicPuzzle_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PicPuzzle_APPL
.PHONY : PicPuzzle_APPL

# fast build rule for target.
PicPuzzle_APPL/fast:
	$(MAKE) -f Samples/Project3/CMakeFiles/PicPuzzle_APPL.dir/build.make Samples/Project3/CMakeFiles/PicPuzzle_APPL.dir/build
.PHONY : PicPuzzle_APPL/fast

#=============================================================================
# Target rules for targets named Launcher_APPL

# Build rule for target.
Launcher_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Launcher_APPL
.PHONY : Launcher_APPL

# fast build rule for target.
Launcher_APPL/fast:
	$(MAKE) -f Samples/Launcher/CMakeFiles/Launcher_APPL.dir/build.make Samples/Launcher/CMakeFiles/Launcher_APPL.dir/build
.PHONY : Launcher_APPL/fast

#=============================================================================
# Target rules for targets named Launcher

# Build rule for target.
Launcher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Launcher
.PHONY : Launcher

# fast build rule for target.
Launcher/fast:
	$(MAKE) -f Samples/Launcher/CMakeFiles/Launcher.dir/build.make Samples/Launcher/CMakeFiles/Launcher.dir/build
.PHONY : Launcher/fast

#=============================================================================
# Target rules for targets named SystemExtension_INIT

# Build rule for target.
SystemExtension_INIT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SystemExtension_INIT
.PHONY : SystemExtension_INIT

# fast build rule for target.
SystemExtension_INIT/fast:
	$(MAKE) -f Samples/SystemExtension/CMakeFiles/SystemExtension_INIT.dir/build.make Samples/SystemExtension/CMakeFiles/SystemExtension_INIT.dir/build
.PHONY : SystemExtension_INIT/fast

#=============================================================================
# Target rules for targets named SystemExtension

# Build rule for target.
SystemExtension: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SystemExtension
.PHONY : SystemExtension

# fast build rule for target.
SystemExtension/fast:
	$(MAKE) -f Samples/SystemExtension/CMakeFiles/SystemExtension.dir/build.make Samples/SystemExtension/CMakeFiles/SystemExtension.dir/build
.PHONY : SystemExtension/fast

#=============================================================================
# Target rules for targets named MPWTool_APPL

# Build rule for target.
MPWTool_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MPWTool_APPL
.PHONY : MPWTool_APPL

# fast build rule for target.
MPWTool_APPL/fast:
	$(MAKE) -f Samples/MPWTool/CMakeFiles/MPWTool_APPL.dir/build.make Samples/MPWTool/CMakeFiles/MPWTool_APPL.dir/build
.PHONY : MPWTool_APPL/fast

#=============================================================================
# Target rules for targets named MPWTool

# Build rule for target.
MPWTool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MPWTool
.PHONY : MPWTool

# fast build rule for target.
MPWTool/fast:
	$(MAKE) -f Samples/MPWTool/CMakeFiles/MPWTool.dir/build.make Samples/MPWTool/CMakeFiles/MPWTool.dir/build
.PHONY : MPWTool/fast

#=============================================================================
# Target rules for targets named Project3Shell

# Build rule for target.
Project3Shell: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Project3Shell
.PHONY : Project3Shell

# fast build rule for target.
Project3Shell/fast:
	$(MAKE) -f Samples/WDEF/CMakeFiles/Project3Shell.dir/build.make Samples/WDEF/CMakeFiles/Project3Shell.dir/build
.PHONY : Project3Shell/fast

#=============================================================================
# Target rules for targets named Project3

# Build rule for target.
Project3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Project3
.PHONY : Project3

# fast build rule for target.
Project3/fast:
	$(MAKE) -f Samples/WDEF/CMakeFiles/Project3.dir/build.make Samples/WDEF/CMakeFiles/Project3.dir/build
.PHONY : Project3/fast

#=============================================================================
# Target rules for targets named Project3Shell_APPL

# Build rule for target.
Project3Shell_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Project3Shell_APPL
.PHONY : Project3Shell_APPL

# fast build rule for target.
Project3Shell_APPL/fast:
	$(MAKE) -f Samples/WDEF/CMakeFiles/Project3Shell_APPL.dir/build.make Samples/WDEF/CMakeFiles/Project3Shell_APPL.dir/build
.PHONY : Project3Shell_APPL/fast

#=============================================================================
# Target rules for targets named LaunchAPPLCommon

# Build rule for target.
LaunchAPPLCommon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LaunchAPPLCommon
.PHONY : LaunchAPPLCommon

# fast build rule for target.
LaunchAPPLCommon/fast:
	$(MAKE) -f LaunchAPPL/Common/CMakeFiles/LaunchAPPLCommon.dir/build.make LaunchAPPL/Common/CMakeFiles/LaunchAPPLCommon.dir/build
.PHONY : LaunchAPPLCommon/fast

#=============================================================================
# Target rules for targets named TestLaunchAPPLCommon

# Build rule for target.
TestLaunchAPPLCommon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestLaunchAPPLCommon
.PHONY : TestLaunchAPPLCommon

# fast build rule for target.
TestLaunchAPPLCommon/fast:
	$(MAKE) -f LaunchAPPL/Common/CMakeFiles/TestLaunchAPPLCommon.dir/build.make LaunchAPPL/Common/CMakeFiles/TestLaunchAPPLCommon.dir/build
.PHONY : TestLaunchAPPLCommon/fast

#=============================================================================
# Target rules for targets named LaunchAPPLServer

# Build rule for target.
LaunchAPPLServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LaunchAPPLServer
.PHONY : LaunchAPPLServer

# fast build rule for target.
LaunchAPPLServer/fast:
	$(MAKE) -f LaunchAPPL/Server/CMakeFiles/LaunchAPPLServer.dir/build.make LaunchAPPL/Server/CMakeFiles/LaunchAPPLServer.dir/build
.PHONY : LaunchAPPLServer/fast

#=============================================================================
# Target rules for targets named LaunchAPPLServer_APPL

# Build rule for target.
LaunchAPPLServer_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LaunchAPPLServer_APPL
.PHONY : LaunchAPPLServer_APPL

# fast build rule for target.
LaunchAPPLServer_APPL/fast:
	$(MAKE) -f LaunchAPPL/Server/CMakeFiles/LaunchAPPLServer_APPL.dir/build.make LaunchAPPL/Server/CMakeFiles/LaunchAPPLServer_APPL.dir/build
.PHONY : LaunchAPPLServer_APPL/fast

#=============================================================================
# Target rules for targets named PascalTrapCPP

# Build rule for target.
PascalTrapCPP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PascalTrapCPP
.PHONY : PascalTrapCPP

# fast build rule for target.
PascalTrapCPP/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/PascalTrapCPP.dir/build.make AutomatedTests/CMakeFiles/PascalTrapCPP.dir/build
.PHONY : PascalTrapCPP/fast

#=============================================================================
# Target rules for targets named PascalTrap_APPL

# Build rule for target.
PascalTrap_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PascalTrap_APPL
.PHONY : PascalTrap_APPL

# fast build rule for target.
PascalTrap_APPL/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/PascalTrap_APPL.dir/build.make AutomatedTests/CMakeFiles/PascalTrap_APPL.dir/build
.PHONY : PascalTrap_APPL/fast

#=============================================================================
# Target rules for targets named PascalTrapCPP_APPL

# Build rule for target.
PascalTrapCPP_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PascalTrapCPP_APPL
.PHONY : PascalTrapCPP_APPL

# fast build rule for target.
PascalTrapCPP_APPL/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/PascalTrapCPP_APPL.dir/build.make AutomatedTests/CMakeFiles/PascalTrapCPP_APPL.dir/build
.PHONY : PascalTrapCPP_APPL/fast

#=============================================================================
# Target rules for targets named Exceptions_APPL

# Build rule for target.
Exceptions_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Exceptions_APPL
.PHONY : Exceptions_APPL

# fast build rule for target.
Exceptions_APPL/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/Exceptions_APPL.dir/build.make AutomatedTests/CMakeFiles/Exceptions_APPL.dir/build
.PHONY : Exceptions_APPL/fast

#=============================================================================
# Target rules for targets named Exceptions

# Build rule for target.
Exceptions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Exceptions
.PHONY : Exceptions

# fast build rule for target.
Exceptions/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/Exceptions.dir/build.make AutomatedTests/CMakeFiles/Exceptions.dir/build
.PHONY : Exceptions/fast

#=============================================================================
# Target rules for targets named File_APPL

# Build rule for target.
File_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 File_APPL
.PHONY : File_APPL

# fast build rule for target.
File_APPL/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/File_APPL.dir/build.make AutomatedTests/CMakeFiles/File_APPL.dir/build
.PHONY : File_APPL/fast

#=============================================================================
# Target rules for targets named Init_APPL

# Build rule for target.
Init_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Init_APPL
.PHONY : Init_APPL

# fast build rule for target.
Init_APPL/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/Init_APPL.dir/build.make AutomatedTests/CMakeFiles/Init_APPL.dir/build
.PHONY : Init_APPL/fast

#=============================================================================
# Target rules for targets named StdIO_APPL

# Build rule for target.
StdIO_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StdIO_APPL
.PHONY : StdIO_APPL

# fast build rule for target.
StdIO_APPL/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/StdIO_APPL.dir/build.make AutomatedTests/CMakeFiles/StdIO_APPL.dir/build
.PHONY : StdIO_APPL/fast

#=============================================================================
# Target rules for targets named Empty_APPL

# Build rule for target.
Empty_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Empty_APPL
.PHONY : Empty_APPL

# fast build rule for target.
Empty_APPL/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/Empty_APPL.dir/build.make AutomatedTests/CMakeFiles/Empty_APPL.dir/build
.PHONY : Empty_APPL/fast

#=============================================================================
# Target rules for targets named PascalTrap

# Build rule for target.
PascalTrap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PascalTrap
.PHONY : PascalTrap

# fast build rule for target.
PascalTrap/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/PascalTrap.dir/build.make AutomatedTests/CMakeFiles/PascalTrap.dir/build
.PHONY : PascalTrap/fast

#=============================================================================
# Target rules for targets named ReallyEmpty

# Build rule for target.
ReallyEmpty: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ReallyEmpty
.PHONY : ReallyEmpty

# fast build rule for target.
ReallyEmpty/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/ReallyEmpty.dir/build.make AutomatedTests/CMakeFiles/ReallyEmpty.dir/build
.PHONY : ReallyEmpty/fast

#=============================================================================
# Target rules for targets named Log

# Build rule for target.
Log: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Log
.PHONY : Log

# fast build rule for target.
Log/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/Log.dir/build.make AutomatedTests/CMakeFiles/Log.dir/build
.PHONY : Log/fast

#=============================================================================
# Target rules for targets named PCRel32_APPL

# Build rule for target.
PCRel32_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PCRel32_APPL
.PHONY : PCRel32_APPL

# fast build rule for target.
PCRel32_APPL/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/PCRel32_APPL.dir/build.make AutomatedTests/CMakeFiles/PCRel32_APPL.dir/build
.PHONY : PCRel32_APPL/fast

#=============================================================================
# Target rules for targets named Init

# Build rule for target.
Init: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Init
.PHONY : Init

# fast build rule for target.
Init/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/Init.dir/build.make AutomatedTests/CMakeFiles/Init.dir/build
.PHONY : Init/fast

#=============================================================================
# Target rules for targets named StdIO

# Build rule for target.
StdIO: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StdIO
.PHONY : StdIO

# fast build rule for target.
StdIO/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/StdIO.dir/build.make AutomatedTests/CMakeFiles/StdIO.dir/build
.PHONY : StdIO/fast

#=============================================================================
# Target rules for targets named PCRel32

# Build rule for target.
PCRel32: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PCRel32
.PHONY : PCRel32

# fast build rule for target.
PCRel32/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/PCRel32.dir/build.make AutomatedTests/CMakeFiles/PCRel32.dir/build
.PHONY : PCRel32/fast

#=============================================================================
# Target rules for targets named ReallyEmpty_APPL

# Build rule for target.
ReallyEmpty_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ReallyEmpty_APPL
.PHONY : ReallyEmpty_APPL

# fast build rule for target.
ReallyEmpty_APPL/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/ReallyEmpty_APPL.dir/build.make AutomatedTests/CMakeFiles/ReallyEmpty_APPL.dir/build
.PHONY : ReallyEmpty_APPL/fast

#=============================================================================
# Target rules for targets named ZeroInitialized

# Build rule for target.
ZeroInitialized: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ZeroInitialized
.PHONY : ZeroInitialized

# fast build rule for target.
ZeroInitialized/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/ZeroInitialized.dir/build.make AutomatedTests/CMakeFiles/ZeroInitialized.dir/build
.PHONY : ZeroInitialized/fast

#=============================================================================
# Target rules for targets named ZeroInitialized_APPL

# Build rule for target.
ZeroInitialized_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ZeroInitialized_APPL
.PHONY : ZeroInitialized_APPL

# fast build rule for target.
ZeroInitialized_APPL/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/ZeroInitialized_APPL.dir/build.make AutomatedTests/CMakeFiles/ZeroInitialized_APPL.dir/build
.PHONY : ZeroInitialized_APPL/fast

#=============================================================================
# Target rules for targets named File

# Build rule for target.
File: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 File
.PHONY : File

# fast build rule for target.
File/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/File.dir/build.make AutomatedTests/CMakeFiles/File.dir/build
.PHONY : File/fast

#=============================================================================
# Target rules for targets named Segments

# Build rule for target.
Segments: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Segments
.PHONY : Segments

# fast build rule for target.
Segments/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/Segments.dir/build.make AutomatedTests/CMakeFiles/Segments.dir/build
.PHONY : Segments/fast

#=============================================================================
# Target rules for targets named Empty

# Build rule for target.
Empty: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Empty
.PHONY : Empty

# fast build rule for target.
Empty/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/Empty.dir/build.make AutomatedTests/CMakeFiles/Empty.dir/build
.PHONY : Empty/fast

#=============================================================================
# Target rules for targets named Log_APPL

# Build rule for target.
Log_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Log_APPL
.PHONY : Log_APPL

# fast build rule for target.
Log_APPL/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/Log_APPL.dir/build.make AutomatedTests/CMakeFiles/Log_APPL.dir/build
.PHONY : Log_APPL/fast

#=============================================================================
# Target rules for targets named Segments_APPL

# Build rule for target.
Segments_APPL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Segments_APPL
.PHONY : Segments_APPL

# fast build rule for target.
Segments_APPL/fast:
	$(MAKE) -f AutomatedTests/CMakeFiles/Segments_APPL.dir/build.make AutomatedTests/CMakeFiles/Segments_APPL.dir/build
.PHONY : Segments_APPL/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... test"
	@echo "... install/local"
	@echo "... retrocrt"
	@echo "... ConsoleTest"
	@echo "... RetroConsole"
	@echo "... ConsoleTest_APPL"
	@echo "... HelloWorld"
	@echo "... HelloWorld_APPL"
	@echo "... AsmTest_APPL"
	@echo "... EmptyTest_APPL"
	@echo "... EmptyTest"
	@echo "... ExceptionTest"
	@echo "... ExceptionTest_APPL"
	@echo "... AsmTest"
	@echo "... InitTest"
	@echo "... InitTest_APPL"
	@echo "... Dialog"
	@echo "... Dialog_APPL"
	@echo "... Raytracer_APPL"
	@echo "... Raytracer"
	@echo "... Raytracer2"
	@echo "... FixedBenchmark"
	@echo "... Raytracer2_APPL"
	@echo "... FixedBenchmark_APPL"
	@echo "... PicPuzzle"
	@echo "... WDEF"
	@echo "... PicPuzzle_APPL"
	@echo "... Launcher_APPL"
	@echo "... Launcher"
	@echo "... SystemExtension_INIT"
	@echo "... SystemExtension"
	@echo "... MPWTool_APPL"
	@echo "... MPWTool"
	@echo "... Project3Shell"
	@echo "... Project3"
	@echo "... Project3Shell_APPL"
	@echo "... LaunchAPPLCommon"
	@echo "... TestLaunchAPPLCommon"
	@echo "... LaunchAPPLServer"
	@echo "... LaunchAPPLServer_APPL"
	@echo "... PascalTrapCPP"
	@echo "... PascalTrap_APPL"
	@echo "... PascalTrapCPP_APPL"
	@echo "... Exceptions_APPL"
	@echo "... Exceptions"
	@echo "... File_APPL"
	@echo "... Init_APPL"
	@echo "... StdIO_APPL"
	@echo "... Empty_APPL"
	@echo "... PascalTrap"
	@echo "... ReallyEmpty"
	@echo "... Log"
	@echo "... PCRel32_APPL"
	@echo "... Init"
	@echo "... StdIO"
	@echo "... PCRel32"
	@echo "... ReallyEmpty_APPL"
	@echo "... ZeroInitialized"
	@echo "... ZeroInitialized_APPL"
	@echo "... File"
	@echo "... Segments"
	@echo "... Empty"
	@echo "... Log_APPL"
	@echo "... Segments_APPL"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

